### ISSUE TITLE
Create a plugin for Canvas integration

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-edx-plugins#3]
In the [lilac branch for residential](https://github.com/mitodl/edx-platform/tree/mitx/lilac), we added a great deal of code to allow for Canvas integration. We should put as much as possible of it into a django plugin that can be pip installed, and run within the edx-platform process. 

### acceptance criteria

- [x] include relevant code from https://github.com/mitodl/edx-platform/commit/006010b36a050fe1a75a1ca3213752d21e260a93
- [x] include relevant code from  mitodl/edx-platform@99656549b4
- [x] include relevant code from  mitodl/edx-platform@b61152ac70
- [x] review code to determine what can go in plugin and what must be part of edx-platform (for example, instructor dashboard front-end code)
- [x] remove any Stellar/LMOD remote gradebook code

**Comment by pdpinch** [comment]
Sorry this wasn't clear. I believe `remote_gradebook` is the app that connects LMS to Stellar/LMOD. We don't want to maintain that connection any more, so you should remove as much of it as you can. 

I think it would be best to move any canvas dependencies into the `canvas_integration` app, but I'm not sure what's easiest.

**Comment by arslanashraf7** [comment]
Closed via https://github.com/mitodl/open-edx-plugins/pull/8, https://github.com/mitodl/edx-platform/pull/274 & as additionally with a documentation PR (https://github.com/mitodl/open-edx-plugins/pull/19).

**Note:** I have created some other tickets(https://github.com/mitodl/open-edx-plugins/issues/10, https://github.com/mitodl/open-edx-plugins/issues/11, https://github.com/mitodl/open-edx-plugins/issues/12, https://github.com/mitodl/open-edx-plugins/issues/13, https://github.com/mitodl/open-edx-plugins/issues/16) in extensions to this epic but they are mostly enhancements/refactor. so I'm closing this ticket and we can work on them independently when suitable.
